name: "Checks"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  checks:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
      - name: Install Native Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --yes libdbus-glib-1-dev libgirepository1.0-dev
      - name: Setup Python
        uses: chrisgavin/setup-python-action@492356cf53b35b71935f2521da0e57af63829c95
      - name: Run
        run: task ci
