name: "Release"

on:
  push:
    tags:
      - "**"

jobs:
  checks:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
      - name: Install Native Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --yes libdbus-glib-1-dev libgirepository1.0-dev
      - name: Setup Python
        uses: chrisgavin/setup-python-action@492356cf53b35b71935f2521da0e57af63829c95
      - name: Run
        run: task publish
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
